service:
  name: vscode-chat-oauth-service

plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-domain-manager

provider:
  name: aws
  runtime: nodejs8.10
  environment: ${file(./env.yml):${opt:stage, self:provider.stage}}

functions:
  slack-redirect:
    handler: handler.slackRedirect
    timeout: 10
    events:
      - http:
          method: get
          path: slack_redirect
  discord-redirect:
    handler: handler.discordRedirect
    timeout: 10
    events:
      - http:
          method: get
          path: discord_redirect
  mattermost-redirect:
    handler: handler.mattermostRedirect
    timeout: 10
    events:
      - http:
          method: get
          path: mattermost_redirect
  home:
    handler: handler.home
    events:
      - http:
          method: get
          path: /

custom:
  customDomain:
    domainName: vscode.chat
    certificateArn: arn:aws:acm:us-east-1:750374355341:certificate/dd3d7f2f-e25f-46b9-8cad-93784e9b2e9b
    stage: ${self:provider.stage}
    createRoute53Record: true
